name: Build and Deploy
on:
  release:
    types:
      - published

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - run: npm build
      - uses: actions/upload-artifact@v3
        with:
          name: built-application
          path: build/
          retention-days: 7
  Deploy:
    runs-on: ubuntu-latest
    name: Deploy Application
    environment: Production
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: built-application
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'pellens'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZ_PUBLISH_PROFILE }}