name: Build
on:
  push:
    branches:
      - '*'

env:
  PUBLIC_EMAIL_CONTACT_ME: ${{ github.actor }}
  PUBLIC_MIXPANEL_API_KEY: ${{ secrets.MIXPANEL_API_KEY }}
  PRISMIC_ENDPOINT_API: ${{ secrets.PRISMIC_ENDPOINT_API }}
  PRISMIC_TOKEN: ${{ secrets.PRISMIC_TOKEN }}
  PRISMIC_DATA_KEY_PROFILE: ${{ secrets.PRISMIC_DATA_KEY_PROFILE }}

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: |
          version="v$(date +%Y.%m.%d%H%M)${{ github.run_number }}"
          release_json=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{\"tag_name\":\"${version}\",\"target_commitish\":\"${{ github.sha }}\",\"name\":\"Release ${version}\",\"draft\":true,\"prerelease\":false,\"generate_release_notes\":true}");
          release_id="$(echo $release_json | jq -r .id)";
          release_tag="$(echo $release_json | jq -r .tag_name)";
          echo "RELEASE_TAG=${release_tag}" >> $GITHUB_OUTPUT;
          echo "RELEASE_ID=${release_id}" >> $GITHUB_OUTPUT;
        id: create-release
      - name: Create Artifact
        run: |
          tar -cvzf app.tar.gz build/ node_modules/ package.json package-lock.json
      - name: Upload Artifact
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create-release.outputs.RELEASE_ID }}/assets?name=app.tar.gz" \
            --data-binary "@app.tar.gz";