name: Build
on:
  push:

env:
  PUBLIC_EMAIL_CONTACT_ME: ${{ github.actor }}
  PUBLIC_MIXPANEL_API_KEY: ${{ secrets.MIXPANEL_API_KEY }}
  PRISMIC_ENDPOINT_API: ${{ secrets.PRISMIC_ENDPOINT_API }}
  PRISMIC_TOKEN: ${{ secrets.PRISMIC_TOKEN }}
  PRISMIC_DATA_KEY_PROFILE: ${{ secrets.PRISMIC_DATA_KEY_PROFILE }}

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: built-application
          path: build/
          retention-days: 7