name: Deploy
on:
  release:
    types:
      - published

jobs:
  Deploy:
    runs-on: ubuntu-latest
    name: Deploy Application
    environment: Production
    steps:
      - run: |
          assets=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets | jq -r .[].browser_download_url);
          for url in $assets; do
            if [ $(echo $assets | grep app.tar.gz) ]; then
              curl -OL $url;
            fi;
          done;
          tar -xvf app.tar.gz;
          rm app.tar.gz;
      - uses: actions/setup-node@v3
        with:
          version: latest
      - run: npm ci
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'pellens'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZ_PUBLISH_PROFILE }}
          package: .